# Build React App
FROM node:latest as build
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app

RUN npm run build

# Serve React App with Nginx
FROM nginx:1.16.0-alpine
COPY .k8s/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]